apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  ACCOUNTS_URI: {{ .Values.routes.accountsUri | quote }}
  CASH_URI: {{ .Values.routes.cashUri | quote }}
  TRANSFER_URI: {{ .Values.routes.transferUri | quote }}
