apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app.kubernetes.io/name: logstash
    app.kubernetes.io/component: logging
spec:
  selector:
    app.kubernetes.io/name: logstash
  ports:
    - name: beats
      port: {{ .Values.service.port }}
      targetPort: beats
