apiVersion: v1
kind: ConfigMap
metadata:
  name: front-ui
  labels:
    {{- include "front-ui.labels" . | nindent 4 }}
data:
  OAUTH_AUTHORIZATION_URI: {{ .Values.oauth.authorizationUri | quote }}
  OAUTH_TOKEN_URI: {{ .Values.global.keycloak.tokenUri | quote }}
  OAUTH_JWK_SET_URI: {{ .Values.global.keycloak.jwkSetUri | quote }}
  OAUTH_USERINFO_URI: {{ .Values.oauth.userInfoUri | quote }}
  GATEWAY_URL: {{ .Values.gatewayUrl | quote }}
  ZIPKIN_ENDPOINT: {{ .Values.global.zipkin.endpoint | quote }}
