spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts
              uri: ${ACCOUNTS_URI:http://localhost:8081}
              predicates:
                - Path=/accounts/**
              filters:
                - StripPrefix=1
            - id: cash
              uri: ${CASH_URI:http://localhost:8083}
              predicates:
                - Path=/cash/**
              filters:
                - StripPrefix=1
            - id: transfer
              uri: ${TRANSFER_URI:http://localhost:8084}
              predicates:
                - Path=/transfer/**
              filters:
                - StripPrefix=1

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
