spring:
  application:
    name: gateway
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}-${random.value}
        prefer-ip-address: true
      config:
        enabled: true
        format: yaml
        prefix: config
        default-context: ${spring.application.name}
        fail-fast: false
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: accounts
              uri: lb://accounts
              predicates:
                - Path=/accounts/**
              filters:
                - StripPrefix=1

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
