apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
data:
  PG_HOST: {{ .Values.global.postgres.host | quote }}
  PG_PORT: {{ .Values.global.postgres.port | quote }}
  PG_DB: {{ .Values.global.postgres.database | quote }}
  PG_USER: {{ .Values.global.postgres.username | quote }}
  OAUTH_ISSUER_URI: {{ .Values.global.keycloak.issuerUri | quote }}
  OAUTH_JWK_SET_URI: {{ .Values.global.keycloak.jwkSetUri | quote }}
  OAUTH_TOKEN_URI: {{ .Values.global.keycloak.tokenUri | quote }}
  OAUTH_CLIENT_ID: {{ .Values.oauth.clientId | quote }}
  NOTIFICATIONS_BASE_URL: {{ .Values.notificationsBaseUrl | quote }}
