apiVersion: v1
kind: Secret
metadata:
  name: accounts
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
type: Opaque
stringData:
  OAUTH_CLIENT_SECRET: {{ .Values.oauth.clientSecret | quote }}
