apiVersion: v1
kind: ConfigMap
metadata:
  name: transfer
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
data:
  OAUTH_ISSUER_URI: {{ .Values.global.keycloak.issuerUri | quote }}
  OAUTH_JWK_SET_URI: {{ .Values.global.keycloak.jwkSetUri | quote }}
  OAUTH_TOKEN_URI: {{ .Values.global.keycloak.tokenUri | quote }}
  OAUTH_CLIENT_ID: {{ .Values.oauth.clientId | quote }}
  ACCOUNTS_BASE_URL: {{ .Values.accountsBaseUrl | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrapServers | quote }}
  BANK_NOTIFICATIONS_TOPIC: {{ .Values.global.kafka.notificationsTopic | quote }}
  ZIPKIN_ENDPOINT: {{ .Values.global.zipkin.endpoint | quote }}
  LOGSTASH_DESTINATION: {{ .Values.global.logstash.destination | quote }}
