spring:
  application:
    name: transfer
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}-${random.value}
        prefer-ip-address: true
      config:
        enabled: true
        format: yaml
        prefix: config
        default-context: ${spring.application.name}
        fail-fast: false

  security:
    oauth2:
      client:
        registration:
          accounts-service:
            client-id: transfer
            client-secret: transfer-service-secret
            authorization-grant-type: client_credentials
            scope: bank:service
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: ${OAUTH_ISSUER_URI:http://localhost:8090/realms/bank}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI:http://localhost:8090/realms/bank}

server:
  port: 8084

bank:
  accounts-base-url: ${ACCOUNTS_BASE_URL:http://accounts}

logging:
  level:
    org.springframework.security: INFO
